
export const About = () => {
  return (
    <>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
      <div>Description</div>
    </>
  )
}

export default About